export const favIcons = {
  'imgflip.com':       'https://imgflip.com/apple-touch-icon.png',
  'ruqqus.com':        'https://ruqqus.com/assets/favicon.ico',
  'tumblr.com':        'https://assets.tumblr.com/images/msfavicon.png',
  'twimg.com':         'https://abs.twimg.com/favicons/twitter.ico',
  'redd.it':           'https://www.redditstatic.com/desktop2x/img/favicon/favicon-32x32.png',
  'depositphotos.com': 'https://webst.depositphotos.com/favicon.ico',
  'discord':           'https://discord.com/assets/07dca80a102d4149e9736d4b162cff6f.ico',
  'clouds.tf':         'https://clouds.tf/panel/img/favicon.ico',
  'thechive.com':      'https://thechive.com/wp-content/themes/chivecommon-2014/assets/images/icons/favicon.png',
  'archive.org':       'https://archive.org/images/glogo.jpg',
  'postimgs.org':      'https://postimgs.org/favicon.ico',
  'postimg.cc':        'https://postimgs.org/favicon.ico',
  'catbox.moe':        'https://catbox.moe/pictures/favicon.ico',
  'ibb.co':            'https://simgbb.com/images/favicon.png',
  'wikimedia.org':     'https://www.wikimedia.org/static/images/project-logos/enwiki.png',
  'redgifs.com':       'https://www.redgifs.com/assets/favicon-32x32.png',
  'gfycat.com':        'https://gfycat.com/assets/favicons/favicon-32x32.png',
  'i.imgur.com':       'https://s.imgur.com/images/favicon-32x32.png',
  'spotify.com':       'https://www.scdn.co/i/_global/touch-icon-72.png',
  'youtube.com':       'https://www.youtube.com/s/desktop/ea048e95/img/favicon_32.png',
  'youtu.be':          'https://www.youtube.com/s/desktop/ea048e95/img/favicon_32.png',
  'amazonaws.com':     'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico'
};
export const favIconsKeys = Object.keys(favIcons);
