export const SETTING_INFINITE_SCROLL = 'SETTING_INFINITE_SCROLL';
export const SETTING_POSTS_NEW_TAB   = 'SETTING_POSTS_NEW_TAB';
export const SETTING_BIGGER_BUTTONS  = 'SETTING_BIGGER_BUTTONS';

export const TYPE_AUTH   = 'TYPE_AUTH';
export const TYPE_UNREAD = 'TYPE_UNREAD';
