export const MOD_INFINITE_SCROLL = 'MOD_INFINITE_SCROLL';
export const MOD_POSTS_NEW_TAB   = 'MOD_POSTS_NEW_TAB';
export const MOD_BIGGER_BUTTONS  = 'MOD_BIGGER_BUTTONS';

export const TYPE_AUTH   = 'TYPE_AUTH';
export const TYPE_UNREAD = 'TYPE_UNREAD';
